### ISSUE TITLE
Name of Game, 'Empyrion - Galactic Survival', in path causes System.ArgumentException

### ISSUE THREAD

**Issue by brcaswell** [GitHub-TC/EmpyrionWebAccess#6]
~~I think this is supposed to be using `EmpriyonConfiguration.SaveGameModPath`~~

https://github.com/GitHub-TC/EmpyrionWebAccess/blob/ce649d660981e6bccb2eb5fdb5e88e132c8e9b74/EmpyrionModWebHost/Controllers/SectorsController.cs#L53

It is attempting to read `Sector/Sector.yaml` at `\\Saves\\Games`

![image](https://user-images.githubusercontent.com/967010/74791414-ff8d5c80-527f-11ea-8ee3-a1ade80422b4.png)

**EDIT**: above screenshot is probably irrelevant, since the `*.yaml` does not exist (we expect an empty `DedicatedYaml.SaveGameName` in that instance) and the path to the yaml file does not reflect the same consideration to this issue

**Comment by brcaswell** [comment]
there are 34 more changes relating to this consideration

![image](https://user-images.githubusercontent.com/967010/74791747-f8b31980-5280-11ea-9b8f-bd7a4ac737a7.png)

**Comment by brcaswell** [comment]
actually.. I don't know why I said that.. I meant both `EmpriyonConfiguration.SaveGameModPath` and `EmpriyonConfiguration.SaveGamePath` are both returning empty string for `DedicatedYaml.SaveGameName` usage.

**Comment by brcaswell** [comment]
The above screenshot was a secondary, the actual issue was observed following the release zip instructions

**20200218 1750_ewa_crash.log**
``` txt
20200218 1750: System.ArgumentException: The directory name 'E:\SteamLibrary\steamapps\common\Empyrion - Galactic Survival\Saves\Games\Sectors' does not exist.
Parameter name: path
   at System.IO.FileSystemWatcher..ctor(String path, String filter)
   at EmpyrionModWebHost.Controllers.SectorsManager..ctor() in T:\EWA\EmpyrionModWebHost\Controllers\SectorsController.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCreateInstance(CreateInstanceCallSite createInstanceCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at EmpyrionModWebHost.Program.Main(String[] args) in T:\EWA\EmpyrionModWebHost\Program.cs:line 53
```
Though the initial MOD\EWS folder was created in the savegame (NewGame_2)
after restarting the server it creates and locks MOD\EWS\DB folder in the parent folder of <savegame>.

here I use LockHunter 
![image](https://user-images.githubusercontent.com/967010/74793404-d66fca80-5285-11ea-940d-3b7b52967b0f.png)

and we can see the process is passed the following args
``` txt
EmpyrionModWebHost.exe
  Process ID: 3232
  Command Line: "E:\SteamLibrary\steamapps\common\Empyrion - Galactic Survival\Content\Mods\EWALoader\EWA\EmpyrionModWebHost.exe" -EmpyrionToModPipe EmpyrionToEWAPipeaf4b9e46dc1d4dcc88700f83ecfd0f17 -ModToEmpyrionPipe EWAToEmpyrionPipef68acff75aa34468893f1024abecec4c -GameDir "E:\SteamLibrary\steamapps\common\Empyrion - Galactic Survival" E:\SteamLibrary\steamapps\common\Empyrion - Galactic Survival\DedicatedServer\EmpyrionDedicated.exe -logFile ../Logs/2777/Dedicated_200218-192323-25.log -dedicated E:\SteamLibrary\steamapps\common\Empyrion - Galactic Survival\Client/../Saves/Games/NewGame_2/dedicated.yaml -gamename NewGame_2 -localdedi
```

**Comment by brcaswell** [comment]
I can't tell at the moment whether the quotes are stripped (and are necessary) or if this is just a copy paste \ dump consideration.
